#! /usr/bin/bash

dir=`dirname "$0"`
cd "$dir"
args=""
while [ $# -gt 0 ]; do
    if [ "$1" = "-h" -o "$1" = "--help" ]; then
        prog=$(basename "$0")
        echo "usage: $prog [-h|--help] [version ...]"
        exit 0
    fi
    if [ -z "$args" ]; then
        args="$1"
    else
        args="$arg $1"
    fi
    shift
done
if [ -z "$args" ]; then
    args=$(echo 0.7 1.{0..11})
fi

for ver in $args; do
    echo "########################################### Julia version $ver"
    rm -f Manifest.toml
    test -r ".Manifest-$ver.toml" && cp -pf ".Manifest-$ver.toml" Manifest.toml
    julia +$ver --color=yes --check-bounds=yes --depwarn=yes --project -e "
        using Pkg;
        Pkg.instantiate();
        Pkg.test();"
    test -r Manifest.toml && mv -f Manifest.toml ".Manifest-$ver.toml"
done
